\c ds3;

ALTER TABLE MEMBERSHIP1 DISABLE TRIGGER ALL;

\COPY MEMBERSHIP1 FROM '..\\..\\..\\data_files\\membership\\membership.csv' WITH DELIMITER ','

ALTER TABLE MEMBERSHIP1 ENABLE TRIGGER ALL;
	

