\c ds3;

ALTER TABLE REVIEWS_HELPFULNESS1 DISABLE TRIGGER ALL;

\COPY REVIEWS_HELPFULNESS1 FROM '..\\..\\..\\data_files\\reviews\\review_helpfulness.csv' WITH DELIMITER ','

ALTER TABLE REVIEWS_HELPFULNESS1 ENABLE TRIGGER ALL;

